### ISSUE TITLE
The original UV range is out of range

### ISSUE THREAD

**Issue by verybigzhouhai** [oguzeroglu/TextureMerger#2]
Hi，
The original UV range is out of range[0,1], e.g. [3,5], is this still applicable?
thx！

**Comment by oguzeroglu** [comment]
Hey,

Sure it is. The `ranges` object produced by TextureMerger is in [0, 1] space. You need to map this range onto your custom UV range. You can use this function:

```javascript
function affineTransformation(oldValue, oldMax, oldMin, newMax, newMin){
  return (((oldValue - oldMin) * (newMax - newMin)) / (oldMax - oldMin)) + newMin;
}
```
You can do this conversion operation in your shaders as well.
